import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Layout.module.css';

import { Settings } from '../components/Settings';
import {
  ContentsContext,
  Introduction,
  Keyboard,
  ScreenReader,
  Link,
  Button,
  Form,
} from '../components/contents';
import { publicPath } from '../utils/publicPath';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>freee Accessibility Training</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={publicPath('favicon.ico')} />
      </Head>

      <header className={styles.header}>
        <hgroup>
          <h1 className={styles.headerTitle}>freee Accessibility Training</h1>
        </hgroup>
      </header>
      <Settings />
      <main className={styles.main}>
        <ContentsContext>
          <Introduction />
          <Keyboard />
          <ScreenReader />
          <Link />
          <Button />
          <Form />
        </ContentsContext>
      </main>
      <footer className={styles.footer}>
        <p>&copy; freee K.K.</p>
        <p>
          <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
            <img
              alt="クリエイティブ・コモンズ・ライセンス"
              style={{ borderWidth: 0 }}
              src="https://i.creativecommons.org/l/by/4.0/88x31.png"
            />
          </a>
          <br />
          このページは
          <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
            クリエイティブ・コモンズ 表示 4.0 国際 ライセンス
          </a>
          の下に提供されています。
        </p>
      </footer>
    </div>
  );
};

export default Home;
